# Generated by Django 2.2.5 on 2021-03-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_amount', models.DecimalField(decimal_places=0, max_digits=2)),
                ('buy_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('address', models.CharField(default='None', max_length=150)),
                ('district', models.CharField(default='None', max_length=30)),
                ('province', models.CharField(default='None', max_length=30)),
                ('zipcode', models.CharField(default='None', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='deliver_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sell_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_time', models.CharField(max_length=10)),
                ('end_warranty', models.DateField()),
                ('buy_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.buy')),
                ('watch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Watch')),
            ],
        ),
        migrations.CreateModel(
            name='deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_date', models.DateField()),
                ('recieve_date', models.DateField()),
                ('deliver_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliver_staff')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='buy',
            name='watch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Watch'),
        ),
    ]
