# Generated by Django 2.2.5 on 2021-04-22 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartwatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Order Canceled', 'Order Canceled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='watch_id',
        ),
        migrations.RemoveField(
            model_name='deliver',
            name='deliver_staff_id',
        ),
        migrations.DeleteModel(
            name='sell_staff',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='watch_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watch',
            name='case',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='watch',
            name='image1',
            field=models.ImageField(blank=True, default='/static/blank.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='watch',
            name='image2',
            field=models.ImageField(blank=True, default='/static/blank.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='watch',
            name='os',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='watch',
            name='warrantys',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='buy',
        ),
        migrations.DeleteModel(
            name='deliver',
        ),
        migrations.DeleteModel(
            name='deliver_staff',
        ),
        migrations.DeleteModel(
            name='warranty',
        ),
        migrations.AddField(
            model_name='cartwatch',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Watch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Watch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.category'),
        ),
    ]
