# Generated by Django 2.2.5 on 2021-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210422_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tel',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
