# Generated by Django 2.2.5 on 2021-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='case',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='dial',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='os',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='warrantys',
        ),
    ]
