# Generated by Django 2.2.5 on 2021-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_watch_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentcardno',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
